### ISSUE TITLE
Current shotwell is not supported

### ISSUE THREAD

**Issue by xb** [fasaxc/shotwell-iphoto-import#2]
Hello,

when trying to import into shotwell 0.14.1, then shotwell-iphoto-import fails and complains that it only supports database schema version 16, while the current shotwell database has schema version 19.

One solution could be to provide an empty version 16 database in the repository such that
1.  an import can be processed based on a copy of the empty version 16 database, and then
2.  the database is migrated from schema version 16 to schema version 19 by shotwell itself.

**Comment by fasaxc** [comment]
Sorry, I don't have much time to devote to this project.  It does sound like a good idea; feel free to submit a pull request ;-)

**Comment by bit-man** [comment]
Curently working on version 20 support + improvements (https://github.com/bit-man/shotwell-iphoto-import/tree/shotwell-version-20-schema-support). Stay tuned !! 
Collaboration is welcome and encouraged :-)

**Comment by bit-man** [comment]
Shotwell version 20 import has been added.
@fasaxc could you close this issue ?
